apiVersion: v1
kind: Pod
metadata:
  name: demo
  labels:
    app: demo
spec:
  restartPolicy: Always
  containers:
    - name: demo-container
      image: demo/demo:v1
      imagePullPolicy: Never
      ports:
        - containerPort: 8081
